# Databricks notebook source
spark.sql("""
CREATE TABLE IF NOT EXISTS default.rag_pdfsdocs_text (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  text STRING
) tblproperties (delta.enableChangeDataFeed = true)
""")

# COMMAND ----------

#to track pdfs
spark.sql("""
CREATE TABLE IF NOT EXISTS default.doc_track(file_name STRING) 
tblproperties (delta.enableChangeDataFeed = true);
""")
